// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: example.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const countExamples = `-- name: CountExamples :one
SELECT COUNT(*)::bigint AS total
FROM example
WHERE ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountExamples(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countExamples, search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countExamplesByName = `-- name: CountExamplesByName :one
SELECT COUNT(*)::bigint AS total
FROM example
WHERE name = $1
`

func (q *Queries) CountExamplesByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countExamplesByName, name)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createExample = `-- name: CreateExample :one
INSERT INTO example (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateExample(ctx context.Context, name string) (Example, error) {
	row := q.db.QueryRow(ctx, createExample, name)
	var i Example
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteExample = `-- name: DeleteExample :exec
DELETE FROM example
WHERE id = $1
`

func (q *Queries) DeleteExample(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExample, id)
	return err
}

const getExample = `-- name: GetExample :one
SELECT id, name, created_at
FROM example
WHERE id = $1
`

func (q *Queries) GetExample(ctx context.Context, id uuid.UUID) (Example, error) {
	row := q.db.QueryRow(ctx, getExample, id)
	var i Example
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listExamples = `-- name: ListExamples :many
SELECT id, name, created_at
FROM example
WHERE ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListExamplesParams struct {
	Search     *string
	PageOffset int
	PageSize   int
}

func (q *Queries) ListExamples(ctx context.Context, arg ListExamplesParams) ([]Example, error) {
	rows, err := q.db.Query(ctx, listExamples, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExampleName = `-- name: UpdateExampleName :one
UPDATE example
SET name = $2
WHERE id = $1
RETURNING id, name, created_at
`

type UpdateExampleNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateExampleName(ctx context.Context, arg UpdateExampleNameParams) (Example, error) {
	row := q.db.QueryRow(ctx, updateExampleName, arg.ID, arg.Name)
	var i Example
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
