// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"time"

	"github.com/google/uuid"
)

type Example struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}
