// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountExamples(ctx context.Context, search *string) (int64, error)
	CountExamplesByName(ctx context.Context, name string) (int64, error)
	CreateExample(ctx context.Context, name string) (Example, error)
	DeleteExample(ctx context.Context, id uuid.UUID) error
	GetExample(ctx context.Context, id uuid.UUID) (Example, error)
	ListExamples(ctx context.Context, arg ListExamplesParams) ([]Example, error)
	UpdateExampleName(ctx context.Context, arg UpdateExampleNameParams) (Example, error)
}

var _ Querier = (*Queries)(nil)
